EventPlanner.CMS/Controllers/EventTypeController.cs
using System;
using System.Web.Mvc;
using EventPlanner.CMS.DataAccess;
using EventPlanner.CMS.Models;
using EventPlanner.CMS.ViewModels.EventVMs;

namespace EventPlanner.CMS.Controllers {
    [Authorize]
    public class EventTypeController : Controller {
        // GET: Event
        [AllowAnonymous]
        public ActionResult Index() {
            var model = new EventType();
            var vm = model.GetAllEventTypes();
            return View("EventTypes", vm);
        }

        // GET: EventType/Create
        public ActionResult Create() {
            return View();
        }

        // POST: EventType/Create
        [HttpPost]
        public ActionResult Create(CreateEditTypeVm vm) {
            try {
                if (!ModelState.IsValid)
                    return View();

                var model = new EventType();
                model.Create(vm.Name);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }

        // GET: EventType/Edit/5
        public ActionResult Edit(int id) {
            var rows = EventTypeDb.GetEventById(id).Rows;
            CreateEditTypeVm vm = new CreateEditTypeVm();
            vm.Id = id;
            vm.Name = rows[0]["Name"].ToString();
            return View(vm);
        }

        // POST: EventType/Edit/5
        [HttpPost]
        public ActionResult Edit(CreateEditTypeVm vm) {
            try {
                var model = new EventType();
                model.Edit(vm.Id, vm.Name);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }

        // POST: EventType/Delete/5
        [HttpPost]
        public ActionResult Delete(int id) {
            try {
                var model = new EventType();
                model.Delete(id);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }
    }
}

EventPlanner.CMS/Controllers/PlaceController.cs
using EventPlanner.CMS.DataAccess;
using EventPlanner.CMS.Models;
using EventPlanner.CMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace EventPlanner.CMS.Controllers {
    [Authorize]
    public class PlaceController : Controller {
        // GET: Place
        public ActionResult Index() {
            var model = new Place();
            var vm = model.GetAllPlaces();
            return View("Places", vm);
        }

        private IEnumerable<PlaceType> GetAllPlaceTypes() {

            var db = PlaceTypeDb.GetAllPlaceTypes();
            var types = new List<PlaceType>();
            foreach (DataRow row in db.Rows) {
                var type = new PlaceType();
                type.Id = (int)row["Id"];
                type.Name = (string)row["Name"];
                types.Add(type);
            }
            return types;
        }

        // GET: Place/Create
        public ActionResult Create() {
            PlaceVm vm = new PlaceVm();
            vm.PlaceTypes = GetAllPlaceTypes();
            return View(vm);
        }

        // POST: Place/Create
        [HttpPost]
        public ActionResult Create(PlaceVm vm) {
            try {
                if (!ModelState.IsValid) {
                    return View();
                }

                var model = new Place();
                model.Create(vm);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }

        // GET: Place/Edit/5
        public ActionResult Edit(int id) {
            var row = PlaceDb.GetPlaceById(id).Rows[0];
            PlaceVm vm = new PlaceVm();
            vm.Id = id;
            vm.Name = row["Name"].ToString();
            vm.Address = row["Address"].ToString();
            vm.CostPerHour = (decimal)row["CostPerHour"];
            vm.PlaceTypeId = (int)row["PlaceTypeId"];
            vm.PlaceTypes = GetAllPlaceTypes();
            return View(vm);
        }

        // POST: Place/Edit/5
        [HttpPost]
        public ActionResult Edit(PlaceVm vm) {
            try {
                var model = new Place();
                model.Edit(vm);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }

        // POST: Place/Delete/5
        [HttpPost]
        public ActionResult Delete(int id) {
            try {
                var model = new Place();
                model.Delete(id);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }
    }
}

EventPlanner.CMS/Controllers/PlaceTypeController.cs
using EventPlanner.CMS.DataAccess;
using EventPlanner.CMS.Models;
using EventPlanner.CMS.ViewModels.EventVMs;
using System;
using System.Web.Mvc;

namespace EventPlanner.CMS.Controllers {
    public class PlaceTypeController : Controller {
        // GET: PlaceType
        public ActionResult Index() {
            var model = new PlaceType();
            var vm = model.GetAllPlaceTypes();
            return View("PlaceTypes", vm);
        }

        // GET: PlaceType/Create
        public ActionResult Create() {
            return View();
        }

        // POST: PlaceType/Create
        [HttpPost]
        public ActionResult Create(CreateEditTypeVm vm) {
            try {
                if (!ModelState.IsValid) {
                    return View();
                }

                var model = new PlaceType();
                model.Create(vm.Name);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }

        // GET: PlaceType/Edit/5
        public ActionResult Edit(int id) {
            var rows = PlaceTypeDb.GetPlaceById(id).Rows;
            CreateEditTypeVm vm = new CreateEditTypeVm();
            vm.Id = id;
            vm.Name = rows[0]["Name"].ToString();
            return View(vm);
        }

        // POST: PlaceType/Edit/5
        [HttpPost]
        public ActionResult Edit(CreateEditTypeVm vm) {
            try {
                var model = new PlaceType();
                model.Edit(vm.Id, vm.Name);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }

        // POST: PlaceType/Delete/5
        [HttpPost]
        public ActionResult Delete(int id) {
            try {
                var model = new PlaceType();
                model.Delete(id);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }
    }
}

EventPlanner.CMS/Controllers/ServiceController.cs
using EventPlanner.CMS.DataAccess;
using EventPlanner.CMS.Models;
using EventPlanner.CMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace EventPlanner.CMS.Controllers {
    public class ServiceController : Controller {
        // GET: Service
        public ActionResult Index() {
            var model = new Service();
            var vm = model.GetAllServices();
            return View("Services", vm);
        }

        // GET: Service/Create
        public ActionResult Create() {
            ServiceVm vm = new ServiceVm();
            vm.ServiceTypes = GetAllServiceTypes();
            return View(vm);
        }

        // POST: Service/Create
        [HttpPost]
        public ActionResult Create(ServiceVm vm) {
            try {
                if (!ModelState.IsValid) {
                    return View();
                }

                var model = new Service();
                model.Create(vm);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }

        // GET: Service/Edit/5
        public ActionResult Edit(int id) {
            var row = ServiceDb.GetServiceById(id).Rows[0];
            ServiceVm vm = new ServiceVm();
            vm.Id = id;
            vm.Name = row["Name"].ToString();
            vm.CostPerHour = (decimal)row["CostPerHour"];
            vm.ServiceTypeId = (int)row["ServiceTypeId"];
            vm.ServiceTypes = GetAllServiceTypes();
            return View(vm);
        }

        private IEnumerable<ServiceType> GetAllServiceTypes() {

            var db = ServiceTypeDb.GetAllServiceTypes();
            var types = new List<ServiceType>();
            foreach (DataRow row in db.Rows) {
                var type = new ServiceType();
                type.Id = (int)row["Id"];
                type.Name = (string)row["Name"];
                types.Add(type);
            }
            return types;
        }

        // POST: Service/Edit/5
        [HttpPost]
        public ActionResult Edit(ServiceVm vm) {
            try {
                var model = new Service();
                model.Edit(vm);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }

        // POST: Service/Delete/5
        [HttpPost]
        public ActionResult Delete(int id) {
            try {
                var model = new Service();
                model.Delete(id);

                return RedirectToAction("Index");
            } catch (Exception ex) {
                return View("Error");
            }
        }
    }
}

EventPlanner.CMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand h1" })

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Home", "Index", "Home", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Event Type", "Index", "EventType", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Place Type", "Index", "PlaceType", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Service Type", "Index", "ServiceType", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Services", "Index", "Service", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Places", "Index", "Place", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>